### ISSUE TITLE
Decoding firebase session cookie fails?

### ISSUE THREAD

**Issue by henryennis** [sveltecasts/003-auth-ssr-firebase-svelte#9]
FirebaseAuthError: Decoding Firebase session cookie failed. Make sure you passed the entire string JWT which represents a session cookie. See https://firebase.google.com/docs/auth/admin/manage-cookies for details on how to retrieve a session cookie.
    at FirebaseAuthError.FirebaseError [as constructor] (C:\Users\henry\Desktop\Dev\sapperFirebaseAdminAuth\node_modules\firebase-admin\lib\utils\error.js:42:28)
    at FirebaseAuthError.PrefixedFirebaseError [as constructor] (C:\Users\henry\Desktop\Dev\sapperFirebaseAdminAuth\node_modules\firebase-admin\lib\utils\error.js:88:28)
    at new FirebaseAuthError (C:\Users\henry\Desktop\Dev\sapperFirebaseAdminAuth\node_modules\firebase-admin\lib\utils\error.js:146:16)
    at FirebaseTokenVerifier.verifyJWT (C:\Users\henry\Desktop\Dev\sapperFirebaseAdminAuth\node_modules\firebase-admin\lib\auth\token-verifier.js:158:35)
    at Auth.BaseAuth.verifySessionCookie (C:\Users\henry\Desktop\Dev\sapperFirebaseAdminAuth\node_modules\firebase-admin\lib\auth\auth.js:318:43)
    at express.use.middleware.session.currentUser (C:\Users\henry\Desktop\Dev\sapperFirebaseAdminAuth\__sapper__\dev\server\server.js:2876:17)
    at Layer.handle [as handle_request] (C:\Users\henry\Desktop\Dev\sapperFirebaseAdminAuth\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\henry\Desktop\Dev\sapperFirebaseAdminAuth\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\henry\Desktop\Dev\sapperFirebaseAdminAuth\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\henry\Desktop\Dev\sapperFirebaseAdminAuth\node_modules\express\lib\router\index.js:335:12) {
  errorInfo: {
    code: 'auth/argument-error',
    message: 'Decoding Firebase session cookie failed. Make sure you passed the entire string JWT which represents a session cookie. See https://firebase.google.com/docs/auth/admin/manage-cookies for details on how to retrieve a session cookie.'
  },
  codePrefix: 'auth'
}
{

**Comment by JeffWScott** [comment]
I also get this.  Everything works locally, but after deploying I get that error above.
